server:
  port: 8888
  servlet:
    context-path: /rp
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rental_platform
    username: root
    password: root
    
mybatis:
  mapper-locations:
  - classpath://mapper/**/*.xml