server:
  port: 8888
  servlet:
    context-path: /rp
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rental_platform?useSSL=false
    username: root
    password: root
    tomcat:
      max-wait: 10000
      max-active: 30
mybatis:
  mapper-locations:
  - classpath:/mapper/**/*.xml
  - classpath:/mapper/*.xml